application: tweet-engine
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /stats.*
  script: appstats/ui.py

- url: /_ah/queue/deferred
  script: deferred.py
  login: admin

- url: /.*
  script: /request.py
